# Generated by Django 6.0 on 2026-01-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='like',
        ),
    ]
