# Generated by Django 6.0 on 2026-02-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_news_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
