# Generated by Django 6.0 on 2026-02-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_news_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news_videos/'),
        ),
    ]
