# Generated by Django 6.0 on 2026-02-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_alter_news_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
