# Generated by Django 6.0 on 2026-02-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_news_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='video',
        ),
        migrations.RemoveField(
            model_name='news',
            name='video_url',
        ),
    ]
